[crs]
projected = "EPSG:2285"

[buffer]
quarter_mile_feet = 1320.0
half_mile_feet = 2640.0

[paths]
transit_stops_csv = 'R:\e2projects_two\SoundCast\Inputs\rtp_2026_2050\networks\2023\base_year_2023_post_rtp\transit_stops.csv'
output_dir = 'Y:\VISION 2050\Data\Displacement\Displacement Index 2026\data\09-Proximity to Current or Future hct'

[output_files]
tract_nowater_csv = "tract2020_gdf_nowater_2023.csv"
area_coverage_csv = "09_futureProximityToTransit.csv"
