[app]
base_year = "2023"

[crs]
projected = "EPSG:2285"
geographic = "EPSG:4326"

[distance]
quarter_mile_feet = 1320.0

[paths]
transit_stops_csv = 'N:\rtp_2026_2050\final_runs\sc_base_year_2023_final\soundcast\inputs\scenario\networks\transit_stops.csv'
parcels_txt = 'C:\Workspace\displacement_index\parcels_urbansim.txt'
hh_persons_h5 = 'N:\rtp_2026_2050\final_runs\sc_base_year_2023_final\soundcast\inputs\scenario\landuse\hh_and_persons.h5'
soundcast_db_url = 'sqlite:///N:/rtp_2026_2050/final_runs/sc_base_year_2023_final/soundcast/inputs/db/soundcast_inputs_2023.db'
output_dir = 'Y:\VISION 2050\Data\Displacement\Displacement Index 2026\data\08-Proximity to Transit'

[output_files]
pop_coverage_csv = "08_proximityToTransit.csv"
map_html = "08_proximityToTransit.csv_map.html"